In [4]:
import pandas as pd 
import requests
from bs4 import BeautifulSoup

In [12]:
# abrir el archivo de inverviones csv y cargarlo a un dataframe
df = pd.read_csv('Archivo_de_Inversiones.csv')
df.head()

  Activo  Precio_Compra Fecha_Compra
0   AAPL          150.0   2023-01-15
1  GOOGL         2800.0   2023-03-10
2   MSFT          300.0   2023-05-20
3   AMZN         3500.0   2023-07-18
4   TSLA          750.0   2023-09-01

In [13]:
def obtener_precio_google_finance(activo):
    try:
        # Construye la URL de búsqueda en Google Finance
        url = f"https://www.google.com/finance/quote/{activo}:NASDAQ"
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        }
        
        # Realiza la solicitud HTTP
        response = requests.get(url, headers=headers)
        if response.status_code != 200:
            print(f"No se pudo obtener datos para {activo}")
            return None
        
        # Parsear el contenido HTML
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Extraer el precio actual (puedes ajustar el selector según el sitio)
        precio = soup.find('div', class_='YMlKec fxKbKc').text.strip()
        return precio
    except Exception as e:
        print(f"Error al obtener el precio de {activo}: {e}")
        return None

# Añadir una columna con los precios
df['Precio_Actual'] = df['Activo'].apply(obtener_precio_google_finance)

df.head()
# # Guardar resultados en un archivo
# df.to_csv('precios_activos.csv', index=False)

# print(df)

  Activo  Precio_Compra Fecha_Compra Precio_Actual
0   AAPL          150.0   2023-01-15       $254.49
1  GOOGL         2800.0   2023-03-10       $191.41
2   MSFT          300.0   2023-05-20       $436.60
3   AMZN         3500.0   2023-07-18       $224.92
4   TSLA          750.0   2023-09-01       $421.06

In [17]:
# convierte Precio_actual a int
df['Precio_Actual'] = df['Precio_Actual'].str.replace(',', '').str.replace('$', '').astype(float)

C:\Users\wadia\AppData\Local\Temp\ipykernel_15792\3893067552.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Precio_Actual'] = df['Precio_Actual'].str.replace(',', '').str.replace('$', '').astype(float)

In [18]:
# calculame la diferencia entre el precio de compra y el precio actual
df['Diferencia'] = df['Precio_Actual'] - df['Precio_Compra']
df.head()

  Activo  Precio_Compra Fecha_Compra  Precio_Actual  Diferencia
0   AAPL          150.0   2023-01-15         254.49      104.49
1  GOOGL         2800.0   2023-03-10         191.41    -2608.59
2   MSFT          300.0   2023-05-20         436.60      136.60
3   AMZN         3500.0   2023-07-18         224.92    -3275.08
4   TSLA          750.0   2023-09-01         421.06     -328.94